// Auto-generated by pocketbase-typegen — run pnpm gen:types after schema changes
// Command: pocketbase-typegen --db ./pb_data/data.db --json > src/shared/types/pocketbase.ts
//
// This file is a placeholder. It will be populated once PocketBase is initialized
// and the schema is created (F1 onwards).
//
// Usage: import type { UsersRecord, StudySessionsRecord } from '@/shared/types/pocketbase'

export type {}
