// Migration 001 — Extend the built-in auth "users" collection
//
// Adds custom profile fields to PocketBase's built-in users auth collection:
//   - displayName: required text (min 2 chars)
//   - friendCode: unique 6-char uppercase alphanumeric (auto-generated by hook)
//   - weeklyGoalMinutes: number, default 600 (= 10 h/week)
//   - timezone: IANA string, default "America/Argentina/Buenos_Aires"
//   - theme: select (auto|light|dark), default "auto"
//   - accentColor: select (sage|blue|warm|mono), default "sage"
//
// PocketBase 0.23.x API:
//   migrate((app) => { ... }, (app) => { ... })
//   app.findCollectionByNameOrId("users") → collection
//   app.save(collection)
//
// Reference: ARCHITECTURE.md §4 users collection

/// <reference path="../pb_data/types.d.ts" />
migrate(
  // UP — add profile fields
  (app) => {
    const collection = app.findCollectionByNameOrId("users");

    // displayName — required, min 2 chars
    collection.fields.addAt(-1, new TextField({
      name: "displayName",
      required: true,
      min: 2,
      max: 100,
    }));

    // friendCode — unique 6-char, required (populated by hook)
    collection.fields.addAt(-1, new TextField({
      name: "friendCode",
      required: true,
      min: 6,
      max: 6,
    }));

    // weeklyGoalMinutes — integer, default 600
    collection.fields.addAt(-1, new NumberField({
      name: "weeklyGoalMinutes",
      required: false,
      min: 30,
      max: 4200,
      onlyInt: true,
    }));

    // timezone — IANA string
    collection.fields.addAt(-1, new TextField({
      name: "timezone",
      required: false,
      max: 100,
    }));

    // theme — select: auto | light | dark
    collection.fields.addAt(-1, new SelectField({
      name: "theme",
      required: false,
      maxSelect: 1,
      values: ["auto", "light", "dark"],
    }));

    // accentColor — select: sage | blue | warm | mono
    collection.fields.addAt(-1, new SelectField({
      name: "accentColor",
      required: false,
      maxSelect: 1,
      values: ["sage", "blue", "warm", "mono"],
    }));

    app.save(collection);
  },

  // DOWN — remove added profile fields
  (app) => {
    const collection = app.findCollectionByNameOrId("users");

    const toRemove = [
      "displayName",
      "friendCode",
      "weeklyGoalMinutes",
      "timezone",
      "theme",
      "accentColor",
    ];

    for (const fieldName of toRemove) {
      const field = collection.fields.getByName(fieldName);
      if (field) {
        collection.fields.remove(field);
      }
    }

    app.save(collection);
  }
);
